# Generated by Django 5.1.6 on 2025-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_computador_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='computador',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
