# Generated by Django 5.1.6 on 2025-02-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_computador_marca_alter_computador_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='computador',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
