# Generated by Django 5.1.6 on 2025-02-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_computador_marca_alter_computador_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='almacenamiento_tipo',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('Híbrido', 'Híbrido')], default='SSD', max_length=50),
        ),
        migrations.AddField(
            model_name='computador',
            name='cantidad_disponible',
            field=models.IntegerField(default=0, help_text='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='almacenamiento',
            field=models.IntegerField(help_text='Capacidad en GB'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='memoria_ram',
            field=models.IntegerField(help_text='Capacidad en GB'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='procesador',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='computador',
            name='rendimiento',
            field=models.FloatField(help_text='Puntuación de rendimiento (1-10)'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='tarjeta_grafica',
            field=models.TextField(),
        ),
    ]
